<!-- BerliOS menu -->
<table BORDER=0 CELLSPACING=0 CELLPADDING=3 WIDTH="100%" BGCOLOR="<?php echo $th_nav_bgcolor;?>">
<tr BGCOLOR="<?php echo $th_navstrip_bgcolor;?>">
<td ALIGN=CENTER>
<span class="titlebar"><font color="<?php echo $th_navstrip_font_color?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SourceLines&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font></span></td>
</tr>

<tr ALIGN=RIGHT BGCOLOR="<?php echo $th_nav_bgcolor;?>">
<td><a href="./" class="menus">About&nbsp;SourceLines</a>
<br><a href="../" class="menus">SourceLines&nbsp;Home</a>
<br>
<br><a href="../doc/documentation.html" class="menus">Documentation</a>
<br><a href="../doc/CHANGELOG" class="menus">Changelog</a>
<br><a href="http://developer.berlios.de/project/filelist.php?group_id=91" class="menus">Download</a>
<br><a href="../doc/LICENSE" class="menus">License</a>
<br>
<br><a href="translating.php" class="menus">Translations</a>
<br><a href="development.php" class="menus">Development</a>
<br><a href="http://developer.berlios.de/cvs/?group_id=91" class="menus">CVS Tree</a>
<br><a href="authors.php" class="menus">Authors</a>
</td>
</tr>
</table>
<!-- end BerliOS menu -->
